from __future__ import annotations
import json
from pathlib import Path
from typing import Any
from processors.opportunity_generation_state import active as active_generation
from processors.opportunity_db_contract import snapshot as db_snapshot

PORTFOLIO=Path('.radar_runtime/founder_current_portfolio.json');CLAIMS=Path('.radar_runtime/r1_current_hypothesis_claims.json');QUEUE=Path('.radar_runtime/market_test_queue_r1.json');SOURCE=Path('.radar_runtime/source_portfolio_v20.json');CAL=Path('.radar_runtime/opportunity_calibration_r1.json');RESEARCH=Path('.radar_runtime/evidence_research_queue_r1.json');WATCH=Path('.radar_runtime/opportunity_watch_signals_r1.json');OUT_JSON=Path('.radar_runtime/founder_opportunity_surface_r1.json');OUT_MD=Path('.radar_runtime/founder_opportunity_surface_r1.md');DISCOVERY=Path('.radar_runtime/opportunity_hypothesis_discovery_r1.json');MARKET_TEST_PACK=Path('.radar_runtime/founder_market_test_pack_r1.md');ACCEPTANCE=Path('.radar_runtime/opportunity_architecture_acceptance_r1.json')
RESEARCH_OBJECTS=Path('.radar_runtime/opportunity_research_objects_a1.json')
ENGINE_VERSION='founder-opportunity-surface-mature-research-a1-evidence-truth'

def _load(p,d):
    try:return json.loads(p.read_text(encoding='utf-8'))
    except:return d

def rebuild_founder_surface()->dict[str,Any]:
    p=_load(PORTFOLIO,{});c=_load(CLAIMS,{});q=_load(QUEUE,{});src=(_load(SOURCE,{}).get('health') or {});cal=_load(CAL,{});disc=_load(DISCOVERY,{});rq=_load(RESEARCH,{});watch=_load(WATCH,{});accept=_load(ACCEPTANCE,{});robj=_load(RESEARCH_OBJECTS,{});state=active_generation();db=db_snapshot();cmap={str(x.get('candidate_id')):x for x in c.get('candidates') or []};tmap={}
    for t in q.get('tests') or []:tmap.setdefault(str(t.get('candidate_id')),[]).append(t)
    items=[]
    for x in p.get('current_hypotheses') or []:
        cl=cmap.get(str(x.get('id')),{});tests=tmap.get(str(x.get('id')),[]);actionable=sorted([t for t in tests if t.get('actionable_now')],key=lambda t:t.get('priority',99));claims=cl.get('claims') or {};supported=[k for k,v in claims.items() if v.get('state')=='SUPPORTED'];unknown=cl.get('next_unknown_claims') or []
        items.append({'id':x.get('id'),'hypothesis_key':x.get('hypothesis_key'),'problem_scope_key':x.get('problem_scope_key'),'problem':x.get('problem') or x.get('title'),'facets':x.get('facet_labels') or [],'actor':x.get('actor'),'workflow':x.get('workflow'),'product':x.get('product_name'),'primary_problem_signature':x.get('primary_problem_signature'),'problem_family_descriptor':x.get('problem_family_descriptor'),'problem_identity_status':x.get('problem_identity_status'),'evidence_disposition':x.get('evidence_disposition'),'opportunity_linkage_status':x.get('opportunity_linkage_status') or 'FRONTIER_NOT_SELF_CERTIFIED','external_enabler_candidate_refs':x.get('external_enabler_candidate_refs') or [],'typed_evidence_bundle':x.get('typed_evidence_bundle'),'evidence_refs':x.get('evidence_refs'),'readiness':x.get('readiness'),'priority_score':x.get('priority_score'),'supported_claims':supported,'externally_updated_claims':cl.get('external_validation_claims_applied') or [],'important_unknowns':unknown[:6],'next_market_test':actionable[0] if actionable else None,'completed_market_tests':sum(t.get('status')=='COMPLETED' for t in tests),'market_status':'UNVALIDATED','venture_opportunity_status':'NOT_SELF_CERTIFIED_RESEARCH_HYPOTHESIS'})
    system={'active_generation':state,'db_contract_status':db.get('status'),'db_contract_fingerprint':db.get('contract_fingerprint'),'db_capabilities':db.get('capabilities'),'source_status':src.get('status'),'source_requests_this_run':src.get('requests_this_run',0),'source_snapshot_network_requests':src.get('snapshot_network_requests',src.get('requests_used',0)),'coverage_boundaries':src.get('coverage_boundaries') or {},'source_contract':src.get('source_contract') or {},'portfolio_quality_gate':p.get('portfolio_quality_gate'),'watch_signal_count':int(watch.get('count',0) or 0),'evidence_research_count':int(rq.get('count',0) or 0),'evidence_research_preview':(rq.get('items') or [])[:12],'research_object_counts':robj.get('counts') or {},'research_objects_path':str(RESEARCH_OBJECTS),'frontier_boundary':robj.get('frontier_boundary'),'evidence_recovery_funnel':disc.get('evidence_recovery_funnel') or {},'relationship_audit':disc.get('relationship_audit') or {},'hypothesis_identity_integrity':disc.get('hypothesis_identity_integrity') or {},'independent_architecture_acceptance':accept,'market_test_pack_path':q.get('market_test_pack_path') or str(MARKET_TEST_PACK),'validation_blocked_reason':q.get('blocked_reason'),'operational_runtime_gate':p.get('operational_usability_gate'),'tests_planned':q.get('tests_planned',0),'tests_actionable_now':q.get('tests_actionable_now',0),'tests_completed':q.get('tests_completed',0),'valid_outcomes':q.get('valid_outcomes',0),'paid_outcomes':q.get('paid_outcomes',0),'outcome_collection_coverage_percent':cal.get('outcome_collection_coverage_percent',0),'candidate_outcome_coverage_percent':cal.get('candidate_outcome_coverage_percent',0),'calibration_dataset_ready':cal.get('calibration_dataset_ready',False),'predictive_accuracy':cal.get('predictive_accuracy','UNVALIDATED')}
    data={'engine_version':ENGINE_VERSION,'current_count':len(items),'current_hypotheses':items,'items':items,'legacy_archive_count':p.get('legacy_archive_count',0),'system_status':system,'predictive_credibility':'UNVALIDATED','truth_contract':'Founder surface shows evidence-backed problem-family research hypotheses, not automatically validated venture opportunities. Incomplete need fragments may survive into research; legacy signatures are optional. Problem/need, market-state and external-enabler evidence remain typed separately. External-enabler × workflow-lag × founder-fit linkage is explicitly frontier and is not self-certified. Runtime self-check never substitutes for human semantic review or market outcomes.'}
    OUT_JSON.parent.mkdir(parents=True,exist_ok=True);OUT_JSON.write_text(json.dumps(data,ensure_ascii=False,indent=2,default=str),encoding='utf-8')
    lines=['# SignalForge Founder Evidence-Backed Research Hypotheses — Mature Research Adoption A1','',f"Current hypotheses: {len(items)} | Watch: {system['watch_signal_count']} | Research queue: {system['evidence_research_count']} | Predictive: UNVALIDATED",f"Runtime gate: {(p.get('operational_usability_gate') or {}).get('mode')} | Independent architecture fixtures: {'PASS' if accept.get('pass') else 'FAIL'} | Valid outcomes: {system['valid_outcomes']} | Paid outcomes: {system['paid_outcomes']}",'', '> A Current item is an evidence-backed problem-family research hypothesis, not a validated venture opportunity. Facets describe evidence; external-enabler candidates do not prove why-now linkage.','']
    for i,x in enumerate(items,1):
        b=x.get('typed_evidence_bundle') or {};lines += [f"## {i}. {x['problem']}",f"- Hypothesis: {x.get('hypothesis_key')}",f"- Facets: {', '.join(x.get('facets') or []) or 'none'}",f"- Actor / workflow: {x.get('actor')} / {x.get('workflow')}",f"- Problem family: {x.get('problem_family_descriptor')}",f"- Legacy primary signature (optional feature): {x.get('primary_problem_signature') or 'none'}",f"- Opportunity linkage: {x.get('opportunity_linkage_status')}",f"- Problem evidence: {', '.join(b.get('problem') or [])}",f"- Independent recurrence: {', '.join(b.get('recurrence') or [])}",f"- Market supply: {', '.join(b.get('market_supply') or []) or 'none'}",f"- External-enabler candidates (context only): {', '.join(b.get('external_enabler_candidates') or []) or 'none'}",f"- Supported claims: {', '.join(x.get('supported_claims') or []) or 'none'}",f"- Important unknowns: {', '.join(x.get('important_unknowns') or []) or 'none'}"]
        t=x.get('next_market_test')
        if t:lines += [f"- Next test: {t.get('test_type')} — {t.get('method')}",f"- Success: {t.get('success_criteria')}"]
        lines += ['']
    lines += ['## Evidence research queue','',f"Count: {system['evidence_research_count']}"]
    for i,r in enumerate((rq.get('items') or [])[:12],1):lines += [f"- {i}. {r.get('problem')}",f"  Missing: {r.get('missing_evidence')} | score={r.get('research_value_score')}"]
    lines += ['','## Runtime / market truth','',f"Independent architecture acceptance: {'PASS' if accept.get('pass') else 'FAIL'}",f"Relationship auditor: {(disc.get('relationship_audit') or {}).get('status')} / {(disc.get('relationship_audit') or {}).get('utility')}",f"Market-test pack: {system['market_test_pack_path']}",f"Market validation: {system['valid_outcomes']} valid outcomes / {system['paid_outcomes']} paid outcomes",f"Predictive accuracy: {system['predictive_accuracy']}",'',json.dumps(system['coverage_boundaries'],ensure_ascii=False)]
    OUT_MD.write_text('\n'.join(lines),encoding='utf-8');return data

def static_acceptance():return {'json_surface':True,'markdown_surface':True,'unique_hypothesis_identity_visible':True,'facets_visible_as_non_identity_metadata':True,'typed_evidence_bundle_visible':True,'independent_architecture_acceptance_visible':True,'relationship_audit_visible':True,'watch_research_visible':True,'market_test_pack_visible':True,'external_validation_visible':True,'predictive_accuracy_not_invented':True,'human_semantic_review_boundary_visible':True,'no_product_ideation':True,'legacy_signature_optional_visible':True,'external_enabler_linkage_not_self_certified':True,'research_objects_visible':True}
