import { Link, useParams } from "react-router-dom";
import { ArrowLeft, ExternalLink } from "lucide-react";
import { useOpportunity, useUpdateOpportunityStatus } from "../api/hooks";
import { CardSkeleton } from "../components/common/Skeleton";

const scores:[string,string][]=[["pain_score","Pain"],["demand_score","Demand"],["growth_score","Growth"],["buyer_score","Buyer signal"],["supply_gap_score","Supply gap (pending external evidence)"],["cross_source_score","Cross-source proof"]];

export default function OpportunityDetail(){
 const id=Number(useParams().id||0), {data:o,isLoading}=useOpportunity(id), update=useUpdateOpportunityStatus();
 if(isLoading)return <CardSkeleton/>; if(!o)return <div className="card">Opportunity not found.</div>;
 return <div className="space-y-4">
  <Link to="/" className="inline-flex gap-1 items-center text-[12px] text-text-secondary"><ArrowLeft size={13}/>Back to Opportunity Radar</Link>
  <div className="card"><div className="flex flex-col lg:flex-row gap-5"><div className="flex-1"><div className="flex gap-2 flex-wrap"><span className="tag">{o.status}</span><span className="tag">{Math.round(o.confidence_score)} confidence</span>{Object.entries(o.source_counts||{}).map(([k,v])=><span key={k} className="tag">{k} {v as number}</span>)}</div><h1 className="text-xl font-semibold mt-2">{o.title}</h1><p className="text-[13px] text-text-secondary mt-3">{o.problem_statement}</p><div className="grid md:grid-cols-2 gap-4 mt-5"><Text label="Who has this problem" value={o.who_has_problem||"Unclear"}/><Text label="Why now" value={o.why_now||"No strong timing evidence yet."}/></div></div>
  <div className="lg:w-56 bg-bg-secondary border border-border-primary rounded-lg p-4"><div className="text-[10px] uppercase text-text-tertiary">Community opportunity signal</div><div className="text-5xl font-semibold font-mono">{Math.round(o.opportunity_score)}</div><div className="text-[11px] text-text-secondary">Confidence {Math.round(o.confidence_score)}/100</div><div className="grid gap-2 mt-4"><button className="btn-secondary text-[11px]" onClick={()=>update.mutate({id:o.id,status:"watch"})}>Watch</button><button className="btn-secondary text-[11px]" onClick={()=>update.mutate({id:o.id,status:"investigate"})}>Investigate</button><button className="btn-secondary text-[11px]" onClick={()=>update.mutate({id:o.id,status:"reject"})}>Dismiss</button></div></div></div></div>
  <div className="grid lg:grid-cols-[1fr_1.2fr] gap-4"><div className="card"><h2 className="text-sm font-medium">Why this score exists</h2><p className="text-[11px] text-text-secondary mt-1">The LLM extracts and verifies the problem; deterministic evidence produces the score. GitHub, Jobs, YC and package supply/demand enrichment is not included yet.</p><div className="space-y-3 mt-4">{scores.map(([k,l])=>{const v=Number((o as any)[k]||0);return <div key={k}><div className="flex justify-between text-[11px]"><span>{l}</span><span className="font-mono">{Math.round(v)}</span></div><div className="h-1.5 bg-bg-tertiary rounded overflow-hidden mt-1"><div className="h-full bg-text-secondary" style={{width:`${Math.max(0,Math.min(100,v))}%`}}/></div></div>})}</div>
  <div className="grid grid-cols-2 gap-3 mt-5 pt-4 border-t border-border-primary"><Text label="Independent users" value={String(o.independent_users)}/><Text label="Evidence" value={String(o.evidence_count)}/><Text label="Cluster cohesion" value={o.cluster_cohesion?.toFixed(3)||"—"}/><Text label="Sources" value={String(Object.keys(o.source_counts||{}).length)}/></div><List label="Workarounds" items={o.workarounds}/><List label="Existing solutions" items={o.existing_solutions}/><List label="Buyer signals" items={o.buyer_signals}/></div>
  <div className="card"><h2 className="text-sm font-medium">Raw evidence</h2><p className="text-[11px] text-text-secondary mt-1">Open original discussions before treating this as a real opportunity.</p><div className="divide-y divide-border-primary mt-3">{(o.evidence||[]).map(e=><div key={e.id} className="py-3"><div className="flex gap-2"><span className="tag">{e.platform||e.source_type}</span>{e.strength!=null&&<span className="text-[10px] text-text-tertiary">evidence {Math.round(e.strength*100)}</span>}</div>{e.title&&<div className="text-[12px] font-medium mt-2">{e.title}</div>}<p className="text-[11px] text-text-secondary mt-1">{e.excerpt}</p>{e.url&&<a href={e.url} target="_blank" rel="noreferrer" className="inline-flex gap-1 items-center text-[10px] text-info mt-2">Original post <ExternalLink size={10}/></a>}</div>)}</div></div></div>
 </div>;
}
function Text({label,value}:{label:string;value:string}){return <div><div className="text-[10px] uppercase tracking-wider text-text-tertiary">{label}</div><div className="text-[12px] mt-1">{value}</div></div>}
function List({label,items}:{label:string;items:string[]}){if(!items?.length)return null;return <div className="mt-5 pt-4 border-t border-border-primary"><div className="text-[10px] uppercase text-text-tertiary">{label}</div><ul className="mt-2 space-y-1">{items.map((x,i)=><li key={i} className="text-[11px] text-text-secondary">• {x}</li>)}</ul></div>}
